package view;

import javax.swing.JOptionPane;

import auth.Auth;
import controllers.AuthController;
import exceptions.AuthenticationException;
import model.bean.User;

public class Tela_login extends javax.swing.JFrame {

    private final AuthController controller;

    /**
     * Creates new form Tela_login
     */
    public Tela_login() {
        initComponents();
        controller = new AuthController();

        if(Auth.check()) {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_EVENTOS = new javax.swing.JLabel();
        btn__entrar = new javax.swing.JButton();
        pwd_senhausuario = new javax.swing.JPasswordField();
        txt_nomeusuario = new javax.swing.JTextField();
        lbl_npcad = new javax.swing.JLabel();
        lbl_cadastrase = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Cadastra-se");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_EVENTOS.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 32)); // NOI18N
        lbl_EVENTOS.setText("EVENTOS");
        lbl_EVENTOS.setToolTipText("");

        btn__entrar.setBackground(new java.awt.Color(0, 212, 146));
        btn__entrar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btn__entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn__entrar.setText("ENTRAR");
        btn__entrar.setBorderPainted(false);
        btn__entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__entrarActionPerformed(evt);
            }
        });

        pwd_senhausuario.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        pwd_senhausuario.setForeground(new java.awt.Color(212, 212, 216));
        pwd_senhausuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pwd_senhausuario.setText("Senha");
        pwd_senhausuario.setToolTipText("");
        pwd_senhausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_senhausuarioActionPerformed(evt);
            }
        });

        txt_nomeusuario.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txt_nomeusuario.setForeground(new java.awt.Color(212, 212, 216));
        txt_nomeusuario.setText("Nome de usuário");
        txt_nomeusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeusuarioActionPerformed(evt);
            }
        });

        lbl_npcad.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        lbl_npcad.setText("Não possui cadastro? ");

        lbl_cadastrase.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        lbl_cadastrase.setForeground(new java.awt.Color(43, 127, 255));
        lbl_cadastrase.setText("Cadastra-se");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwd_senhausuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_nomeusuario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_npcad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cadastrase)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(lbl_EVENTOS)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn__entrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_EVENTOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(txt_nomeusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwd_senhausuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_npcad)
                    .addComponent(lbl_cadastrase))
                .addGap(18, 18, 18)
                .addComponent(btn__entrar)
                .addGap(12, 12, 12))
        );

        pwd_senhausuario.getAccessibleContext().setAccessibleName("campo_senha");
        pwd_senhausuario.getAccessibleContext().setAccessibleParent(pwd_senhausuario);
        txt_nomeusuario.getAccessibleContext().setAccessibleName("campo_usuario");
        txt_nomeusuario.getAccessibleContext().setAccessibleParent(lbl_EVENTOS);

        jPanel2.setBackground(new java.awt.Color(43, 127, 255));
        jPanel2.setForeground(new java.awt.Color(43, 127, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeusuarioActionPerformed

    private void btn__entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__entrarActionPerformed
        String username = txt_nomeusuario.getText();
        String password = "";
        for (char c : pwd_senhausuario.getPassword()) {
            password += c;
        }

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            return;
        }

        try {
            User user = this.controller.login(username, password);
            if (user != null) {
                this.dispose();

                //TODO: renderizar a pagina inicial

            } else {
                throw new AuthenticationException("Erro ao efetuar login!");
            }
        } catch (AuthenticationException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn__entrarActionPerformed

    private void pwd_senhausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_senhausuarioActionPerformed

    }//GEN-LAST:event_pwd_senhausuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn__entrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbl_EVENTOS;
    private javax.swing.JLabel lbl_cadastrase;
    private javax.swing.JLabel lbl_npcad;
    private javax.swing.JPasswordField pwd_senhausuario;
    private javax.swing.JTextField txt_nomeusuario;
    // End of variables declaration//GEN-END:variables
}
