package view;

import java.awt.Color;
import java.awt.Dimension;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import controllers.InscricaoController;
import exceptions.AuthenticationException;
import exceptions.DomainException;
import exceptions.InvalidInputException;
import model.bean.Atividade;
import model.bean.Evento;
import model.bean.Inscricao;
import model.bean.User;
import usecases.CSFindEventoById;
import usecases.CSFindUserByID;
import usecases.CSListarAtividades;

public class Tela_inscricao_eventos extends javax.swing.JFrame {

    private final InscricaoController controller = new InscricaoController();
    private Long id_evento = 2L;

    public Tela_inscricao_eventos setEventoId(Long id) {
        this.id_evento = id;
        return this;
    }

    private void loadCategorias() {
        String[] categorias = new String[]{"Estudante", "Servidor", "Público Externo"};

        for (String categoria : categorias) {
            this.select_categoria.addItem(categoria);
        }
    }

    private void loadAtividades() {
        List<Atividade> atividades = new CSListarAtividades().execute(this.id_evento);
        if (atividades == null) {
            return;
        }

        for (Atividade a : atividades) {
            String titulo = a.getTitulo();
            String horaInicio = a.getHora_inicio().toString();
            String horaTermino = a.getHora_termino().toString();

            JPanel item = new JPanel();
            item.setLayout(new BoxLayout(item, BoxLayout.X_AXIS));
            item.setBackground(new Color(240, 240, 240));
            item.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

            JLabel lblTitulo = new JLabel(titulo);
            lblTitulo.setPreferredSize(new Dimension(300, 20));
            JLabel lblHorario = new JLabel(" " + horaInicio + " - " + horaTermino);
            lblHorario.setForeground(Color.DARK_GRAY);

            item.add(lblTitulo);
            item.add(Box.createHorizontalGlue());
            item.add(lblHorario);

            pnl_atividades.add(item);
        }

        pnl_atividades.revalidate();
        pnl_atividades.repaint();
    }

    private void loadEvento() {
        Evento evento = new CSFindEventoById().execute(this.id_evento);

        if (evento == null) {
            JOptionPane.showMessageDialog(this, "Evento nao encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            new Tela_Inicial().setVisible(true);
            this.dispose();
            return;
        }

        txt_titulo.setText(evento.getTitulo());
        txt_descricao.setText(evento.getDescricao());
        txt_formato.setText(evento.getFormato().toString());
        txt_data_inicio.setText(evento.getDataInicio().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txt_data_termino.setText(evento.getDataTermino().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        User organizador = new CSFindUserByID().execute(evento.getId_organizador());
        if (organizador != null) {
            txt_organizador.setText(organizador.getNome());
        } else {
            txt_organizador.setText("Organizador desconhecido");
        }
    }

    public Tela_inscricao_eventos() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        pnl_atividades.setLayout(new BoxLayout(pnl_atividades, BoxLayout.Y_AXIS));
        pnl_atividades.setBackground(Color.WHITE);

        String texto = "<html><font color = 'WHITE'>Este sistema tem como objetivo gerenciar os eventos organizados<br>pelo Instituto Federal de Educação, Ciência e Tecnologia de<br>Rondônia - Campus Calama (IFRO), oferecendo ferramentas para<br>cadastro, divulgação, inscrições, controle de participante e<br>emissão de certificados</html>";
        lbl_descricaosistema.setText(texto);

        loadCategorias();
        loadAtividades();
        loadEvento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_topo = new javax.swing.JPanel();
        lbl_topoevento = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        pnl_descricao = new javax.swing.JPanel();
        lbl_linkevento = new javax.swing.JLabel();
        lbl_linkatividades = new javax.swing.JLabel();
        lbl_linkcronograma = new javax.swing.JLabel();
        lbl_descricaosistema = new javax.swing.JLabel();
        lbl_titulosistema = new javax.swing.JLabel();
        lbl_links = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_inscrever = new javax.swing.JButton();
        txt_descricao = new javax.swing.JLabel();
        txt_data_inicio = new javax.swing.JLabel();
        lbl_descricaoevento = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JLabel();
        scr_atividades = new javax.swing.JScrollPane();
        pnl_atividades = new javax.swing.JPanel();
        txt_data_termino = new javax.swing.JLabel();
        txt_formato = new javax.swing.JLabel();
        lbl_Categoria = new javax.swing.JLabel();
        lbl_AtvEventos = new javax.swing.JLabel();
        pnl_menupesquisa = new javax.swing.JPanel();
        lbl_inicio = new javax.swing.JLabel();
        lbl_componente1 = new javax.swing.JLabel();
        lbl_inscricaoevento = new javax.swing.JLabel();
        lbl_componente02 = new javax.swing.JLabel();
        lbl_eventos = new javax.swing.JLabel();
        txt_organizador = new javax.swing.JLabel();
        lb_select_categoria = new javax.swing.JLabel();
        select_categoria = new javax.swing.JComboBox<>();
        lb_data_inicio = new javax.swing.JLabel();
        lb_organizador = new javax.swing.JLabel();
        lb_data_termino = new javax.swing.JLabel();
        lbl_formato = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnl_topo.setBackground(new java.awt.Color(255, 255, 255));

        lbl_topoevento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_topoevento.setText("EVENTOS");

        btn_inicio.setBackground(new java.awt.Color(0, 212, 146));
        btn_inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicio.setText("Início");
        btn_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inicioMouseClicked(evt);
            }
        });
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_topoLayout = new javax.swing.GroupLayout(pnl_topo);
        pnl_topo.setLayout(pnl_topoLayout);
        pnl_topoLayout.setHorizontalGroup(
            pnl_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_topoevento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_topoLayout.setVerticalGroup(
            pnl_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_topoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_topoevento)
                    .addComponent(btn_inicio))
                .addContainerGap())
        );

        pnl_descricao.setBackground(new java.awt.Color(51, 51, 51));

        lbl_linkevento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_linkevento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linkevento.setText("• Eventos");

        lbl_linkatividades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_linkatividades.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linkatividades.setText("• Atividades");

        lbl_linkcronograma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_linkcronograma.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linkcronograma.setText("• Cronograma");

        lbl_titulosistema.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulosistema.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_titulosistema.setForeground(new java.awt.Color(60, 181, 132));
        lbl_titulosistema.setText("SISTEMA DE GERENCIAMENTO DE EVENTOS");

        lbl_links.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_links.setForeground(new java.awt.Color(60, 181, 132));
        lbl_links.setText("Links");

        javax.swing.GroupLayout pnl_descricaoLayout = new javax.swing.GroupLayout(pnl_descricao);
        pnl_descricao.setLayout(pnl_descricaoLayout);
        pnl_descricaoLayout.setHorizontalGroup(
            pnl_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_descricaoLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addGroup(pnl_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_titulosistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_descricaosistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119)
                .addGroup(pnl_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_linkcronograma)
                    .addComponent(lbl_linkevento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_links)
                    .addComponent(lbl_linkatividades, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 133, Short.MAX_VALUE))
        );
        pnl_descricaoLayout.setVerticalGroup(
            pnl_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_descricaoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_links)
                    .addComponent(lbl_titulosistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_descricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_descricaoLayout.createSequentialGroup()
                        .addComponent(lbl_linkevento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_linkatividades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_linkcronograma))
                    .addGroup(pnl_descricaoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_descricaosistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_inscrever.setBackground(new java.awt.Color(0, 212, 146));
        btn_inscrever.setForeground(new java.awt.Color(255, 255, 255));
        btn_inscrever.setText("Realizar inscrição");
        btn_inscrever.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscreverActionPerformed(evt);
            }
        });

        txt_descricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_descricao.setForeground(new java.awt.Color(102, 102, 102));
        txt_descricao.setText("descrição");
        txt_descricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_data_inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_data_inicio.setText("data inicio");

        lbl_descricaoevento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_descricaoevento.setText("Descrição do Evento");

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_titulo.setText("Titulo Evento");

        scr_atividades.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnl_atividades.setBackground(new java.awt.Color(255, 255, 255));
        pnl_atividades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnl_atividadesLayout = new javax.swing.GroupLayout(pnl_atividades);
        pnl_atividades.setLayout(pnl_atividadesLayout);
        pnl_atividadesLayout.setHorizontalGroup(
            pnl_atividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        pnl_atividadesLayout.setVerticalGroup(
            pnl_atividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        scr_atividades.setViewportView(pnl_atividades);

        txt_data_termino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_data_termino.setText("data final");

        txt_formato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_formato.setText("formato");

        lbl_Categoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Categoria.setText("Categoria de inscrição");

        lbl_AtvEventos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_AtvEventos.setText("Atividades  do Evento");

        pnl_menupesquisa.setBackground(new java.awt.Color(255, 255, 255));
        pnl_menupesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_inicio.setText("Inicio");
        lbl_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_inicioMouseClicked(evt);
            }
        });

        lbl_componente1.setText(">");

        lbl_inscricaoevento.setText("Inscrição");

        lbl_componente02.setText(">");

        lbl_eventos.setText("Eventos");

        javax.swing.GroupLayout pnl_menupesquisaLayout = new javax.swing.GroupLayout(pnl_menupesquisa);
        pnl_menupesquisa.setLayout(pnl_menupesquisaLayout);
        pnl_menupesquisaLayout.setHorizontalGroup(
            pnl_menupesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menupesquisaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_componente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_inscricaoevento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_componente02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_eventos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_menupesquisaLayout.setVerticalGroup(
            pnl_menupesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menupesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_menupesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inicio)
                    .addComponent(lbl_componente1)
                    .addComponent(lbl_inscricaoevento)
                    .addComponent(lbl_componente02)
                    .addComponent(lbl_eventos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_organizador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_organizador.setText("Organizador responsável");

        lb_select_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_select_categoria.setText("Selecione a sua categoria:");

        select_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        select_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        lb_data_inicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_data_inicio.setText("Data de início:");

        lb_organizador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_organizador.setText("Organizador:");

        lb_data_termino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_data_termino.setText("Data de término:");

        lbl_formato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_formato.setText("Formato:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menupesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Categoria)
                            .addComponent(lbl_descricaoevento)
                            .addComponent(lb_select_categoria)
                            .addComponent(select_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_AtvEventos))
                        .addContainerGap(721, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lb_data_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_organizador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_data_termino, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_organizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_data_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_data_termino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txt_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scr_atividades, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(pnl_menupesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_organizador)
                    .addComponent(txt_organizador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_data_inicio)
                    .addComponent(lb_data_inicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_data_termino)
                    .addComponent(txt_data_termino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formato)
                    .addComponent(lbl_formato))
                .addGap(30, 30, 30)
                .addComponent(lbl_descricaoevento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_AtvEventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_atividades, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lbl_Categoria)
                .addGap(18, 18, 18)
                .addComponent(lb_select_categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_topo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_topo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscreverActionPerformed
        String categoria = select_categoria.getSelectedItem().toString().trim().toUpperCase();

        Inscricao inscricao = new Inscricao();

        inscricao.setId_evento(this.id_evento);
        inscricao.setCategoria(categoria);

        try {
            boolean sucesso = this.controller.store(inscricao);

            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Inscrição realizada com sucesso!", "Inscrição", JOptionPane.INFORMATION_MESSAGE);

                //TODO: renderizar a tela do cronograma do usuario
            }
        } catch (AuthenticationException | DomainException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_inscreverActionPerformed

    private void btn_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicioMouseClicked

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        new Tela_Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void lbl_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_inicioMouseClicked
        new Tela_Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_inicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_inscricao_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_inscricao_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_inscricao_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_inscricao_eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_inscricao_eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_inscrever;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_data_inicio;
    private javax.swing.JLabel lb_data_termino;
    private javax.swing.JLabel lb_organizador;
    private javax.swing.JLabel lb_select_categoria;
    private javax.swing.JLabel lbl_AtvEventos;
    private javax.swing.JLabel lbl_Categoria;
    private javax.swing.JLabel lbl_componente02;
    private javax.swing.JLabel lbl_componente1;
    private javax.swing.JLabel lbl_descricaoevento;
    private javax.swing.JLabel lbl_descricaosistema;
    private javax.swing.JLabel lbl_eventos;
    private javax.swing.JLabel lbl_formato;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JLabel lbl_inscricaoevento;
    private javax.swing.JLabel lbl_linkatividades;
    private javax.swing.JLabel lbl_linkcronograma;
    private javax.swing.JLabel lbl_linkevento;
    private javax.swing.JLabel lbl_links;
    private javax.swing.JLabel lbl_titulosistema;
    private javax.swing.JLabel lbl_topoevento;
    private javax.swing.JPanel pnl_atividades;
    private javax.swing.JPanel pnl_descricao;
    private javax.swing.JPanel pnl_menupesquisa;
    private javax.swing.JPanel pnl_topo;
    private javax.swing.JScrollPane scr_atividades;
    private javax.swing.JComboBox<String> select_categoria;
    private javax.swing.JLabel txt_data_inicio;
    private javax.swing.JLabel txt_data_termino;
    private javax.swing.JLabel txt_descricao;
    private javax.swing.JLabel txt_formato;
    private javax.swing.JLabel txt_organizador;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
