/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Kassandra Oliveira
 */
public class Tela_cadastro_atividades extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cadastro_atividades
     */
    public Tela_cadastro_atividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cadastroevento = new javax.swing.JLabel();
        lbl_atividades = new javax.swing.JLabel();
        lbl_geral = new javax.swing.JLabel();
        lbl_organizadores = new javax.swing.JLabel();
        txt_localatividade = new javax.swing.JTextField();
        btn_voltar = new javax.swing.JButton();
        lbl_diahora = new javax.swing.JLabel();
        txt_horainicio = new javax.swing.JTextField();
        lbl_horainicio = new javax.swing.JLabel();
        lbl_dataatividade = new javax.swing.JLabel();
        lbl_horatermino = new javax.swing.JLabel();
        txt_dataatividade = new javax.swing.JTextField();
        txt_horatermino = new javax.swing.JTextField();
        lbl_dialocal = new javax.swing.JLabel();
        lbl_inicio = new javax.swing.JLabel();
        lbl_cadastro02 = new javax.swing.JLabel();
        lbl_atividades02 = new javax.swing.JLabel();
        lbl_componente1 = new javax.swing.JLabel();
        lbl_componente02 = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        lbl_categoria = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        bnt_salvar = new javax.swing.JButton();
        lbl_ATIVIDADES = new javax.swing.JLabel();
        txt_nomeatividades = new javax.swing.JTextField();
        lbl_nomeatividades = new javax.swing.JLabel();
        lbl_quantdias = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        txt_quantdias = new javax.swing.JTextField();
        lbl_categoria = new javax.swing.JLabel();
        lbl_ambientes = new javax.swing.JLabel();
        lbl_localatividade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lbl_cadastroevento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_cadastroevento.setText("Cadastro de eventos");
        lbl_cadastroevento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_atividades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_atividades.setText("• Atividades");

        lbl_geral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_geral.setText("◦ Geral");

        lbl_organizadores.setText("◦ Organizadores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_organizadores)
                            .addComponent(lbl_atividades)
                            .addComponent(lbl_geral)))
                    .addComponent(lbl_cadastroevento))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cadastroevento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_geral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_atividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_organizadores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_localatividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_localatividadeActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        bnt_salvar.setBackground(new java.awt.Color(0, 212, 146));
        bnt_salvar.setForeground(new java.awt.Color(255, 255, 255));
        bnt_salvar.setText("Salvar");
        bnt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_salvarActionPerformed(evt);
            }
        });

        lbl_horainicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_horainicio.setText("Hora de início:");

        lbl_dataatividade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_dataatividade.setText("Data da atividade:");

        lbl_horatermino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_horatermino.setText("Hora de término:");

        txt_dataatividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataatividadeActionPerformed(evt);
            }
        });

        txt_horatermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantdiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_cadastroatividadesLayout = new javax.swing.GroupLayout(pnl_cadastroatividades);
        pnl_cadastroatividades.setLayout(pnl_cadastroatividadesLayout);
        pnl_cadastroatividadesLayout.setHorizontalGroup(
            pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bnt_salvar)
                .addGap(27, 27, 27))
            .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_inicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_componente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_cadastro02)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_componente02)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_atividades02))
                    .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ATIVIDADES)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ambientes)
                            .addComponent(lbl_data)
                            .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_categoria, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nomeatividades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_nomeatividades)
                                    .addComponent(lbl_categoria)
                                    .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                                        .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_dataatividade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_dataatividade))
                                        .addGap(166, 166, 166)
                                        .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_quantdias)
                                            .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                                                .addComponent(txt_quantdias, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_confirmadata))))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_cadastroatividadesLayout.setVerticalGroup(
            pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inicio)
                    .addComponent(lbl_cadastro02)
                    .addComponent(lbl_atividades02)
                    .addComponent(lbl_componente1)
                    .addComponent(lbl_componente02))
                .addGap(18, 18, 18)
                .addComponent(lbl_ATIVIDADES)
                .addGap(6, 6, 6)
                .addComponent(lbl_nomeatividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomeatividades, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lbl_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                        .addComponent(lbl_dataatividade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dataatividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_cadastroatividadesLayout.createSequentialGroup()
                        .addComponent(lbl_quantdias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_confirmadata)
                            .addComponent(txt_quantdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ambientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_cadastroatividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(bnt_salvar))
                .addContainerGap())
        );

        lbl_inicio.setText("Inicio");

        lbl_cadastro02.setText("Cadastro");

        lbl_atividades02.setText("Atividades");

        lbl_componente1.setText(">");

        lbl_componente02.setText(">");

        lbl_data.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_data.setText("• Data");

        bnt_salvar.setBackground(new java.awt.Color(0, 212, 146));
        bnt_salvar.setForeground(new java.awt.Color(255, 255, 255));
        bnt_salvar.setText("Salvar");
        bnt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_salvarActionPerformed(evt);
            }
        });

        lbl_ATIVIDADES.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_ATIVIDADES.setText("• Atividades");

        txt_nomeatividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeatividadesActionPerformed(evt);
            }
        });

        lbl_nomeatividades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nomeatividades.setText("Nome da atividade:");

        lbl_quantdias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_quantdias.setText("Quantidade de dias:");

        txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriaActionPerformed(evt);
            }
        });

        txt_quantdias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantdiasActionPerformed(evt);
            }
        });

        lbl_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_categoria.setText("Categoria:");

        lbl_ambientes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_ambientes.setText("• Ambientes");

        lbl_localatividade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_localatividade.setText("Local da atividade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bnt_salvar)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_inicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_componente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_cadastro02)
                                .addGap(6, 6, 6)
                                .addComponent(lbl_componente02)
                                .addGap(6, 6, 6)
                                .addComponent(lbl_atividades02))
                            .addComponent(lbl_ATIVIDADES)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_dialocal)
                                    .addComponent(lbl_nomeatividades)
                                    .addComponent(lbl_ambientes)
                                    .addComponent(lbl_localatividade)
                                    .addComponent(txt_localatividade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_voltar)
                                    .addComponent(lbl_categoria)
                                    .addComponent(txt_nomeatividades, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_data)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_dataatividade)
                                            .addComponent(txt_dataatividade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_horainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_horainicio)
                                            .addComponent(lbl_diahora))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_quantdias, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_quantdias)
                                            .addComponent(lbl_horatermino)
                                            .addComponent(txt_horatermino, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(312, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(416, 416, 416))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ATIVIDADES)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_nomeatividades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomeatividades, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dataatividade)
                            .addComponent(lbl_quantdias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dataatividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quantdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(lbl_diahora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_horatermino)
                            .addComponent(lbl_horainicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_horatermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_horainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ambientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_dialocal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_localatividade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_localatividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnt_salvar)
                    .addComponent(btn_voltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_localatividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_localatividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localatividadeActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void txt_horainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_horainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataatividadeActionPerformed

    private void txt_dataatividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataatividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataatividadeActionPerformed

    private void txt_horaterminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_horaterminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantdiasActionPerformed

    private void bnt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_salvarActionPerformed

    private void txt_nomeatividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeatividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeatividadesActionPerformed

    private void txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoriaActionPerformed

    private void txt_quantdiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantdiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantdiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro_atividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_salvar;
    private javax.swing.JButton btn_confirmadata;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_ATIVIDADES;
    private javax.swing.JLabel lbl_ambientes;
    private javax.swing.JLabel lbl_atividades;
    private javax.swing.JLabel lbl_atividades02;
    private javax.swing.JLabel lbl_cadastro02;
    private javax.swing.JLabel lbl_cadastroevento;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_componente02;
    private javax.swing.JLabel lbl_componente1;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_dataatividade;
    private javax.swing.JLabel lbl_descricaosistema;
    private javax.swing.JLabel lbl_geral;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JLabel lbl_linkatividades;
    private javax.swing.JLabel lbl_linkcronograma;
    private javax.swing.JLabel lbl_linkevento;
    private javax.swing.JLabel lbl_links;
    private javax.swing.JLabel lbl_menudescricao;
    private javax.swing.JLabel lbl_nomeatividades;
    private javax.swing.JLabel lbl_organizadores;
    private javax.swing.JLabel lbl_quantdias;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_dataatividade;
    private javax.swing.JTextField txt_nomeatividades;
    private javax.swing.JTextField txt_quantdias;
    // End of variables declaration//GEN-END:variables
}
