
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JFrame;

/**
 *
 * @author Kassandra Oliveira
 */
public class Tela_cadastro_eventos_geral extends javax.swing.JFrame {

  private boolean isDataValida(String dataStr) {
        if (dataStr == null || dataStr.isEmpty()) return false;

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // não permite datas inválidas como 32/01/2023

        try {
            sdf.parse(dataStr);
            return true;
        } catch (java.text.ParseException e) {
            return false;
        }
    }


    public Tela_cadastro_eventos_geral() {
        initComponents();
        
        lbl_menuatividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_menuatividades.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispose(); // fecha a tela de login 
                Tela_cadastro_atividades cadastro = new Tela_cadastro_atividades();
                cadastro.setVisible(true);
            }
        });
        
                lbl_menuorganizadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_menuorganizadores.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispose(); // fecha a tela de login 
                Tela_cadastro_organizador og = new Tela_cadastro_organizador();
                og.setVisible(true);
            }
        });
        


        //faz com q abra em tela cheia
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        String texto = "<html><font color = 'GRAY'>Preencha os formulários<br>com as informações<br>do seu evento.</html>";
        lbl_menudescricao.setText(texto);
        
        String texto2 = "<html><font color = 'WHITE'>Este sistema tem como objetivo gerenciar os eventos organizados<br>pelo Instituto Federal de Educação, Ciência e Tecnologia de<br>Rondônia - Campus Calama (IFRO), oferecendo ferramentas para<br>cadastro, divulgação, inscrições, controle de participante e<br>emissão de certificados</html>";
        lbl_descricaosistema.setText(texto2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        lbl_cadastrogeral = new javax.swing.JLabel();
        lbl_menueventos = new javax.swing.JLabel();
        lbl_menuatividades = new javax.swing.JLabel();
        lbl_menuorganizadores = new javax.swing.JLabel();
        lbl_menudescricao = new javax.swing.JLabel();
        pnl_topo = new javax.swing.JPanel();
        lbl_topoevento = new javax.swing.JLabel();
        pnl_eventos = new javax.swing.JPanel();
        lbl_informainicio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_informacadastro = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_informaevento = new javax.swing.JLabel();
        lbl_eventos = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_descricao = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        lbl_formato = new javax.swing.JLabel();
        lbl_categoria = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        lbl_data = new javax.swing.JLabel();
        lbl_datainicio = new javax.swing.JLabel();
        txt_datainicio = new javax.swing.JTextField();
        lbl_localizacao = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        lbl_datafim = new javax.swing.JLabel();
        txt_datafim = new javax.swing.JTextField();
        lbl_local = new javax.swing.JLabel();
        txt_local = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        lbl_cidade = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        cmb_formato = new javax.swing.JComboBox<>();
        pnl_descrição = new javax.swing.JPanel();
        lbl_titulosistema = new javax.swing.JLabel();
        lbl_links = new javax.swing.JLabel();
        lbl_linkevento = new javax.swing.JLabel();
        lbl_linkatividades = new javax.swing.JLabel();
        lbl_linkcronograma = new javax.swing.JLabel();
        lbl_descricaosistema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnl_menu.setBackground(new java.awt.Color(234, 234, 234));

        lbl_cadastrogeral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_cadastrogeral.setText("Cadastro Geral");
        lbl_cadastrogeral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_menueventos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_menueventos.setText("• Eventos");

        lbl_menuatividades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_menuatividades.setText("◦ Atividades");

        lbl_menuorganizadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_menuorganizadores.setText("◦ Organizadores");

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_menudescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_cadastrogeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_menuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_menuorganizadores)
                            .addComponent(lbl_menuatividades)
                            .addComponent(lbl_menueventos))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_cadastrogeral, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_menudescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_menueventos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_menuatividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_menuorganizadores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_topo.setBackground(new java.awt.Color(255, 255, 255));

        lbl_topoevento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_topoevento.setText("EVENTOS");

        javax.swing.GroupLayout pnl_topoLayout = new javax.swing.GroupLayout(pnl_topo);
        pnl_topo.setLayout(pnl_topoLayout);
        pnl_topoLayout.setHorizontalGroup(
            pnl_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_topoevento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_topoLayout.setVerticalGroup(
            pnl_topoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_topoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_topoevento)
                .addContainerGap())
        );

        pnl_eventos.setBackground(new java.awt.Color(255, 255, 255));

        lbl_informainicio.setText("Inicio");

        jLabel10.setText(">");

        lbl_informacadastro.setText("Cadastro");

        jLabel11.setText(">");

        lbl_informaevento.setText("Eventos");

        lbl_eventos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_eventos.setText("• Eventos");

        lbl_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nome.setText("Nome do evento:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_descricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_descricao.setText("Descrição do evento:");

        txt_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descricaoActionPerformed(evt);
            }
        });

        lbl_formato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_formato.setText("Formato do evento:");

        lbl_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_categoria.setText("Categoria do evento:");

        txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriaActionPerformed(evt);
            }
        });

        lbl_data.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_data.setText("• Data");

        lbl_datainicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_datainicio.setText("Inicio do evento:");

        txt_datainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datainicioActionPerformed(evt);
            }
        });

        lbl_localizacao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_localizacao.setText("• Localização");

        lbl_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_estado.setText("Estado:");

        lbl_datafim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_datafim.setText("Fim do evento:");

        txt_datafim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datafimActionPerformed(evt);
            }
        });

        lbl_local.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_local.setText("Local:");

        txt_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_localActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(0, 212, 146));
        btn_salvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        lbl_cidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cidade.setText("Cidade:");

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        cmb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Presencial", "Hibrido" }));

        javax.swing.GroupLayout pnl_eventosLayout = new javax.swing.GroupLayout(pnl_eventos);
        pnl_eventos.setLayout(pnl_eventosLayout);
        pnl_eventosLayout.setHorizontalGroup(
            pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_eventosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_eventosLayout.createSequentialGroup()
                        .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_eventos)
                            .addGroup(pnl_eventosLayout.createSequentialGroup()
                                .addComponent(lbl_informainicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_informacadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_informaevento))
                            .addGroup(pnl_eventosLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_formato, 0, 230, Short.MAX_VALUE)
                                    .addComponent(lbl_estado)
                                    .addComponent(lbl_categoria)
                                    .addComponent(lbl_descricao)
                                    .addComponent(lbl_nome)
                                    .addComponent(lbl_formato)
                                    .addComponent(lbl_datainicio)
                                    .addComponent(txt_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(txt_categoria)
                                    .addComponent(txt_datainicio)
                                    .addComponent(txt_nome)
                                    .addComponent(cmb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_datafim)
                                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_datafim, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55)
                        .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_eventosLayout.createSequentialGroup()
                                .addComponent(txt_local, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_salvar))
                            .addComponent(lbl_local)))
                    .addGroup(pnl_eventosLayout.createSequentialGroup()
                        .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_data)
                            .addComponent(lbl_localizacao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_eventosLayout.setVerticalGroup(
            pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_eventosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_informainicio)
                    .addComponent(jLabel10)
                    .addComponent(lbl_informacadastro)
                    .addComponent(jLabel11)
                    .addComponent(lbl_informaevento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_eventos)
                .addGap(12, 12, 12)
                .addComponent(lbl_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_descricao)
                .addGap(12, 12, 12)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_formato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_categoria)
                .addGap(9, 9, 9)
                .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbl_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_datainicio)
                    .addComponent(lbl_datafim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_datainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_datafim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lbl_localizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_estado)
                    .addComponent(lbl_cidade)
                    .addComponent(lbl_local))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pnl_descrição.setBackground(new java.awt.Color(51, 51, 51));

        lbl_titulosistema.setBackground(new java.awt.Color(255, 255, 255));
        lbl_titulosistema.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_titulosistema.setForeground(new java.awt.Color(60, 181, 132));
        lbl_titulosistema.setText("SISTEMA DE GERENCIAMENTO DE EVENTOS");

        lbl_links.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl_links.setForeground(new java.awt.Color(60, 181, 132));
        lbl_links.setText("Links");

        lbl_linkevento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_linkevento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linkevento.setText("• Eventos");

        lbl_linkatividades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_linkatividades.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linkatividades.setText("• Atividades");

        lbl_linkcronograma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_linkcronograma.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linkcronograma.setText("• Cronograma");

        javax.swing.GroupLayout pnl_descriçãoLayout = new javax.swing.GroupLayout(pnl_descrição);
        pnl_descrição.setLayout(pnl_descriçãoLayout);
        pnl_descriçãoLayout.setHorizontalGroup(
            pnl_descriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_descriçãoLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addGroup(pnl_descriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_titulosistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_descricaosistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119)
                .addGroup(pnl_descriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_linkcronograma)
                    .addComponent(lbl_linkevento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_links)
                    .addComponent(lbl_linkatividades, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 113, Short.MAX_VALUE))
        );
        pnl_descriçãoLayout.setVerticalGroup(
            pnl_descriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_descriçãoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl_descriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_links)
                    .addComponent(lbl_titulosistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_descriçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_descriçãoLayout.createSequentialGroup()
                        .addComponent(lbl_linkevento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_linkatividades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_linkcronograma))
                    .addGroup(pnl_descriçãoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_descricaosistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_descrição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_topo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_eventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnl_topo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_eventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_descrição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
    String nome = txt_nome.getText().trim();         // Nome do evento
    String descricao = txt_descricao.getText().trim();    // Descrição do evento
    String categoria = txt_categoria.getText().trim();    // Categoria
    String dataInicio = txt_datainicio.getText().trim();   // Data de início
    String dataFim = txt_datafim.getText().trim();      // Data de fim
    String cidade = txt_cidade.getText().trim();       // Cidade
    String campus = txt_local.getText().trim();       // Campus
    String estado = cmb_estado.getSelectedItem().toString(); // Estado
    String formato = cmb_formato.getSelectedItem().toString(); // Formato

    // Verificação de campos obrigatórios
    if (nome.isEmpty() || descricao.isEmpty() || categoria.isEmpty() ||
        dataInicio.isEmpty() || dataFim.isEmpty() || cidade.isEmpty() || campus.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validação de datas
    if (!isDataValida(dataInicio) || !isDataValida(dataFim)) {
        JOptionPane.showMessageDialog(this, "Datas inválidas! Use o formato dd/MM/yyyy.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Mensagem de confirmação com resumo dos dados
    JOptionPane.showMessageDialog(this,
        "Evento salvo com sucesso!\n\n"
        + "Nome: " + nome + "\n"
        + "Descrição: " + descricao + "\n"
        + "Categoria: " + categoria + "\n"
        + "Formato: " + formato + "\n"
        + "Data de início: " + dataInicio + "\n"
        + "Data de fim: " + dataFim + "\n"
        + "Local: " + campus + " - " + cidade + ", " + estado + "\n",
        "Sucesso", JOptionPane.INFORMATION_MESSAGE


    );
    
        dispose(); // fecha a tela de login 
        Tela_cadastro_organizador cadastro = new Tela_cadastro_organizador();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_datainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datainicioActionPerformed

    private void txt_datafimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datafimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datafimActionPerformed

    private void txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoriaActionPerformed

    private void txt_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_localActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localActionPerformed

    private void txt_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_eventos_geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_eventos_geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_eventos_geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_eventos_geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro_eventos_geral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JComboBox<String> cmb_formato;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lbl_cadastrogeral;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_datafim;
    private javax.swing.JLabel lbl_datainicio;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_descricaosistema;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_eventos;
    private javax.swing.JLabel lbl_formato;
    private javax.swing.JLabel lbl_informacadastro;
    private javax.swing.JLabel lbl_informaevento;
    private javax.swing.JLabel lbl_informainicio;
    private javax.swing.JLabel lbl_linkatividades;
    private javax.swing.JLabel lbl_linkcronograma;
    private javax.swing.JLabel lbl_linkevento;
    private javax.swing.JLabel lbl_links;
    private javax.swing.JLabel lbl_local;
    private javax.swing.JLabel lbl_localizacao;
    private javax.swing.JLabel lbl_menuatividades;
    private javax.swing.JLabel lbl_menudescricao;
    private javax.swing.JLabel lbl_menueventos;
    private javax.swing.JLabel lbl_menuorganizadores;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_titulosistema;
    private javax.swing.JLabel lbl_topoevento;
    private javax.swing.JPanel pnl_descrição;
    private javax.swing.JPanel pnl_eventos;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_topo;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_datafim;
    private javax.swing.JTextField txt_datainicio;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_local;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
